window.JUMPFIRST_CONTENT = {
  translations: {
    th: {
      navAbout: 'เกี่ยวกับ',
      navCourses: 'คอร์สเรียน',
      navContact: 'ติดต่อ',
      login: 'เข้าสู่ระบบ',
      register: 'สมัครสมาชิก',
      heroEyebrow: 'ระบบคอร์สเรียนที่ตอบโจทย์ทุกขั้นตอน',
      heroTitle: 'เรียนรู้ได้อย่างง่ายดาย พร้อมระบบสมาชิกที่ครบครัน',
      heroDesc: 'JumpFirst Academy ออกแบบให้คุณลงทะเบียนเรียน จัดการตารางเรียน และติดตามสถานะคอร์สได้ในพื้นที่เดียว',
      heroCtaRegister: 'ลงทะเบียนเรียน',
      heroCtaLogin: 'เข้าสู่ระบบ',
      heroHighlight1: 'ระบบสมาชิกปลอดภัย',
      heroHighlight2: 'ลงทะเบียนเรียนง่าย',
      heroHighlight3: 'จัดการตารางเรียนได้เอง',
      dashboardPreview: 'ตัวอย่างแดชบอร์ด',
      dashboardTitle: 'ภาพรวมแดชบอร์ด',
      statCourses: 'คอร์สที่เข้าร่วม',
      statSchedule: 'ตารางเรียนใหม่',
      statSuccess: 'ความสำเร็จ',
      aboutEyebrow: 'เกี่ยวกับเรา',
      aboutTitle: 'สร้างประสบการณ์การเรียนรู้ที่ราบรื่นและสบายตา',
      aboutDesc: 'เราออกแบบเว็บไซต์ด้วยความตั้งใจให้ทุกคนใช้งานง่าย ทั้งนักเรียน ผู้ปกครอง และทีมงานด้านการศึกษา ที่สำคัญคือเน้นให้ทุกฟีเจอร์เข้าถึงได้ง่ายจากทุกอุปกรณ์',
      aboutCardTitle: 'สิ่งที่ผู้ใช้จะได้รับ',
      aboutItem1: 'ระบบสมาชิกที่ใช้งานง่าย',
      aboutItem2: 'การลงทะเบียนเรียนแบบไม่ซับซ้อน',
      aboutItem3: 'ระบบติดต่อและคำถามที่รวดเร็ว',
      coursesEyebrow: 'ข้อมูลคอร์สเรียน',
      coursesTitle: 'คอร์สที่น่าสนใจสำหรับการเติบโตของคุณ',
      course1Title: 'พื้นฐาน Frontend',
      course1Desc: 'เรียนรู้ HTML, CSS และ JavaScript สำหรับสร้างเว็บที่สวยงามและใช้งานง่าย',
      course1Level: 'ระดับพื้นฐาน',
      course2Title: 'ออกแบบ UX/UI',
      course2Desc: 'ฝึกออกแบบหน้าตาเว็บให้สอดคล้องกับผู้ใช้งานและสร้างประสบการณ์ที่ดี',
      course2Level: 'ระดับกลาง',
      course3Title: 'เติบโตสายอาชีพ',
      course3Desc: 'เตรียมตัวสำหรับงานด้านเทคโนโลยีด้วยทักษะที่จำเป็นในยุคปัจจุบัน',
      course3Level: 'ระดับเชิงลึก',
      registerEyebrow: 'ลงทะเบียนเรียน',
      registerTitle: 'เริ่มต้นการเรียนรู้ด้วยขั้นตอนที่ชัดเจน',
      registerDesc: 'เลือกคอร์สที่คุณสนใจ กรอกข้อมูลให้ครบ แล้วรอรับคำแนะนำจากทีมงาน',
      registerStep1: 'เลือกคอร์สที่ต้องการ',
      registerStep2: 'กรอกข้อมูลและยืนยันการสมัคร',
      registerStep3: 'รับตารางเรียนและเริ่มเรียนทันที',
      registerAction: 'สนใจลงทะเบียน',
      memberEyebrow: 'ข้อมูลสมาชิก',
      memberTitle: 'บริหารข้อมูลและติดตามสถานะคอร์สในแดชบอร์ดเดียว',
      memberDesc: 'สมาชิกสามารถดูข้อมูลส่วนตัว แก้ไขข้อมูล และจัดการตารางเรียนจากหน้าจอเดียวกัน',
      memberNameLabel: 'ชื่อสมาชิก',
      memberNameValue: 'นภัสสรณ์ แสงศรี',
      memberStatusLabel: 'สถานะคอร์ส',
      memberStatusValue: 'กำลังเรียน',
      memberScheduleLabel: 'ตารางเรียน',
      memberScheduleValue: 'จัดการแล้ว 3 รายการ',
      memberManageBtn: 'จัดการตารางเรียน',
      contactEyebrow: 'ติดต่อ',
      contactTitle: 'ติดต่อเราได้ทันที',
      contactDesc: 'หากมีคำถามหรืออยากขอคำแนะนำ สามารถส่งข้อความถึงเราได้เลย',
      contactNamePlaceholder: 'ชื่อของคุณ',
      contactEmailPlaceholder: 'อีเมล',
      contactMessagePlaceholder: 'ข้อความของคุณ',
      contactSubmit: 'ส่งข้อความ',
      footerTagline: 'ออกแบบเพื่อประสบการณ์การเรียนรู้ที่ลื่นไหล',
      close: 'ปิด',
      loginTitle: 'เข้าสู่ระบบ',
      loginIdentifierPlaceholder: 'Username / Email / เบอร์โทรศัพท์',
      loginPasswordPlaceholder: 'รหัสผ่าน',
      loginSubmit: 'เข้าสู่ระบบ',
      registerTitleModal: 'สร้างบัญชีใหม่',
      registerFullNamePlaceholder: 'ชื่อ-สกุล',
      registerPhonePlaceholder: 'เบอร์โทรศัพท์',
      registerEmailPlaceholder: 'อีเมล',
      registerUsernamePlaceholder: 'ชื่อผู้ใช้',
      registerPasswordPlaceholder: 'รหัสผ่าน',
      registerSubmit: 'สมัครสมาชิก',
      contactSent: 'ข้อความของคุณถูกส่งเรียบร้อยแล้ว จะติดต่อกลับโดยเร็วที่สุด',
      backToTop: 'กลับขึ้นด้านบน',
      themeLight: 'สว่าง',
      themeDark: 'มืด',
      switchToDark: 'สลับเป็นโหมดมืด',
      switchToLight: 'สลับเป็นโหมดสว่าง',
      switchLanguage: 'สลับภาษา'
    },
    en: {
      navAbout: 'About',
      navCourses: 'Courses',
      navContact: 'Contact',
      login: 'Login',
      register: 'Register',
      heroEyebrow: 'Course platform for every learning step',
      heroTitle: 'Learn with ease through a complete member experience',
      heroDesc: 'JumpFirst Academy lets you register courses, manage schedules, and track learning progress in one place.',
      heroCtaRegister: 'Join a Course',
      heroCtaLogin: 'Sign In',
      heroHighlight1: 'Secure member system',
      heroHighlight2: 'Simple enrollment flow',
      heroHighlight3: 'Self-managed schedules',
      dashboardPreview: 'Dashboard preview',
      dashboardTitle: 'Dashboard Overview',
      statCourses: 'Courses joined',
      statSchedule: 'New schedules',
      statSuccess: 'Success rate',
      aboutEyebrow: 'About Us',
      aboutTitle: 'A smooth and comfortable learning experience',
      aboutDesc: 'We design this platform for easy access across students, parents, and education teams, with clear flows on every device.',
      aboutCardTitle: 'What users get',
      aboutItem1: 'Easy-to-use member tools',
      aboutItem2: 'Simple enrollment process',
      aboutItem3: 'Fast communication support',
      coursesEyebrow: 'Course Catalog',
      coursesTitle: 'Programs built for your growth',
      course1Title: 'Frontend Essentials',
      course1Desc: 'Learn HTML, CSS, and JavaScript to build beautiful, usable websites.',
      course1Level: 'Beginner level',
      course2Title: 'UX/UI Design',
      course2Desc: 'Design interfaces that match user needs and deliver better experiences.',
      course2Level: 'Intermediate level',
      course3Title: 'Career Growth',
      course3Desc: 'Prepare for tech careers with skills that matter in today\'s market.',
      course3Level: 'Advanced level',
      registerEyebrow: 'Enrollment',
      registerTitle: 'Start learning with clear steps',
      registerDesc: 'Pick your course, complete your details, and get guided by our team.',
      registerStep1: 'Choose your preferred course',
      registerStep2: 'Fill in details and confirm',
      registerStep3: 'Receive schedule and start learning',
      registerAction: 'I want to enroll',
      memberEyebrow: 'Member Area',
      memberTitle: 'Manage profile and course status in one dashboard',
      memberDesc: 'Members can view profile details, edit information, and handle schedules in one place.',
      memberNameLabel: 'Member Name',
      memberNameValue: 'Napatsorn Saengsri',
      memberStatusLabel: 'Course Status',
      memberStatusValue: 'In progress',
      memberScheduleLabel: 'Schedule',
      memberScheduleValue: '3 items managed',
      memberManageBtn: 'Manage Schedule',
      contactEyebrow: 'Contact',
      contactTitle: 'Contact us anytime',
      contactDesc: 'If you have questions or need guidance, send us a message anytime.',
      contactNamePlaceholder: 'Your name',
      contactEmailPlaceholder: 'Your email',
      contactMessagePlaceholder: 'Your message',
      contactSubmit: 'Send Message',
      footerTagline: 'Designed for a smooth learning experience.',
      close: 'Close',
      loginTitle: 'Login',
      loginIdentifierPlaceholder: 'Username / Email / Phone number',
      loginPasswordPlaceholder: 'Password',
      loginSubmit: 'Login',
      registerTitleModal: 'Create a new account',
      registerFullNamePlaceholder: 'Full name',
      registerPhonePlaceholder: 'Phone number',
      registerEmailPlaceholder: 'Email',
      registerUsernamePlaceholder: 'Username',
      registerPasswordPlaceholder: 'Password',
      registerSubmit: 'Register',
      contactSent: 'Your message was sent successfully. We will contact you soon.',
      backToTop: 'Back to top',
      themeLight: 'Light',
      themeDark: 'Dark',
      switchToDark: 'Switch to dark mode',
      switchToLight: 'Switch to light mode',
      switchLanguage: 'Switch language'
    }
  },
  textBindings: [
    ['.site-nav a:nth-child(1)', 'navAbout'],
    ['.site-nav a:nth-child(2)', 'navCourses'],
    ['.site-nav a:nth-child(3)', 'navContact'],
    ['.nav-actions .btn.btn-secondary[data-open-modal="loginModal"]', 'login'],
    ['.nav-actions .btn.btn-primary[data-open-modal="registerModal"]', 'register'],
    ['.hero-copy .eyebrow', 'heroEyebrow'],
    ['.hero-copy h1', 'heroTitle'],
    ['.hero-copy > p:not(.eyebrow)', 'heroDesc'],
    ['.hero-actions .btn.btn-primary', 'heroCtaRegister'],
    ['.hero-actions .btn.btn-outline[data-open-modal="loginModal"]', 'heroCtaLogin'],
    ['.hero-highlights li:nth-child(1)', 'heroHighlight1'],
    ['.hero-highlights li:nth-child(2)', 'heroHighlight2'],
    ['.hero-highlights li:nth-child(3)', 'heroHighlight3'],
    ['.card-body h3', 'dashboardTitle'],
    ['.stats-grid div:nth-child(1) span', 'statCourses'],
    ['.stats-grid div:nth-child(2) span', 'statSchedule'],
    ['.stats-grid div:nth-child(3) span', 'statSuccess'],
    ['#about .eyebrow', 'aboutEyebrow'],
    ['#about h2', 'aboutTitle'],
    ['#about .section-grid > div:first-child p:not(.eyebrow)', 'aboutDesc'],
    ['#about .info-card h3', 'aboutCardTitle'],
    ['#about .info-card li:nth-child(1)', 'aboutItem1'],
    ['#about .info-card li:nth-child(2)', 'aboutItem2'],
    ['#about .info-card li:nth-child(3)', 'aboutItem3'],
    ['#courses .section-heading .eyebrow', 'coursesEyebrow'],
    ['#courses .section-heading h2', 'coursesTitle'],
    ['#courses .feature-card:nth-child(1) h3', 'course1Title'],
    ['#courses .feature-card:nth-child(1) p', 'course1Desc'],
    ['#courses .feature-card:nth-child(1) span', 'course1Level'],
    ['#courses .feature-card:nth-child(2) h3', 'course2Title'],
    ['#courses .feature-card:nth-child(2) p', 'course2Desc'],
    ['#courses .feature-card:nth-child(2) span', 'course2Level'],
    ['#courses .feature-card:nth-child(3) h3', 'course3Title'],
    ['#courses .feature-card:nth-child(3) p', 'course3Desc'],
    ['#courses .feature-card:nth-child(3) span', 'course3Level'],
    ['#register .eyebrow', 'registerEyebrow'],
    ['#register h2', 'registerTitle'],
    ['#register .section-grid > div:first-child p:not(.eyebrow)', 'registerDesc'],
    ['#register .step:nth-child(1) p', 'registerStep1'],
    ['#register .step:nth-child(2) p', 'registerStep2'],
    ['#register .step:nth-child(3) p', 'registerStep3'],
    ['#register .register-panel .btn.btn-primary', 'registerAction'],
    ['#member .eyebrow', 'memberEyebrow'],
    ['#member h2', 'memberTitle'],
    ['#member .section-grid > div:first-child p:not(.eyebrow)', 'memberDesc'],
    ['#member .member-row:nth-child(1) strong', 'memberNameLabel'],
    ['#member .member-row:nth-child(1) span', 'memberNameValue'],
    ['#member .member-row:nth-child(2) strong', 'memberStatusLabel'],
    ['#member .member-row:nth-child(2) span', 'memberStatusValue'],
    ['#member .member-row:nth-child(3) strong', 'memberScheduleLabel'],
    ['#member .member-row:nth-child(3) span', 'memberScheduleValue'],
    ['#member .member-card .btn.btn-secondary', 'memberManageBtn'],
    ['#contact .eyebrow', 'contactEyebrow'],
    ['#contact h2', 'contactTitle'],
    ['#contact .contact-wrap > div p:not(.eyebrow)', 'contactDesc'],
    ['#contactForm .btn.btn-primary', 'contactSubmit'],
    ['.footer-wrap p:last-child', 'footerTagline'],
    ['#loginTitle', 'loginTitle'],
    ['#loginModal .btn.btn-primary', 'loginSubmit'],
    ['#registerTitle', 'registerTitleModal'],
    ['#registerModal .btn.btn-primary', 'registerSubmit']
  ],
  placeholderBindings: [
    ['#contactForm input[type="text"]', 'contactNamePlaceholder'],
    ['#contactForm input[type="email"]', 'contactEmailPlaceholder'],
    ['#contactForm textarea', 'contactMessagePlaceholder'],
    ['#loginModal input[type="text"]', 'loginIdentifierPlaceholder'],
    ['#loginModal input[type="password"]', 'loginPasswordPlaceholder'],
    ['#registerModal input[type="text"]:nth-of-type(1)', 'registerFullNamePlaceholder'],
    ['#registerModal input[type="tel"]', 'registerPhonePlaceholder'],
    ['#registerModal input[type="email"]', 'registerEmailPlaceholder'],
    ['#registerModal input[type="text"]:nth-of-type(2)', 'registerUsernamePlaceholder'],
    ['#registerModal input[type="password"]', 'registerPasswordPlaceholder']
  ]
};
