(function () {
  const store = window.JUMPFIRST_CONTENT || {
    translations: { th: {}, en: {} },
    textBindings: [],
    placeholderBindings: []
  };

  Object.assign(store.translations.th, {
    navHome: 'หน้าแรก',
    loginPageEyebrow: 'เข้าสู่ระบบ',
    loginPageTitle: 'ยินดีต้อนรับกลับสู่ JUMPFIRST',
    loginPageDesc: 'เข้าสู่ระบบเพื่อจัดการคอร์ส ดูตารางเรียน และติดตามความคืบหน้าของคุณได้ทันที',
    loginPageHighlight1: 'เข้าถึงแดชบอร์ดสมาชิก',
    loginPageHighlight2: 'อัปเดตตารางเรียนแบบเรียลไทม์',
    loginPageHighlight3: 'ติดตามสถานะคอร์สได้ตลอดเวลา',
    loginFormTitle: 'เข้าสู่ระบบ',
    loginRemember: 'จดจำฉันในอุปกรณ์นี้',
    loginHelperLink: 'ยังไม่มีบัญชี? สมัครสมาชิก',
    loginFooterTagline: 'การเข้าถึงสมาชิกที่รวดเร็วและปลอดภัย',
    loginIdentifierPlaceholder: 'Username / Email / เบอร์โทรศัพท์',
    loginPasswordPlaceholder: 'รหัสผ่าน',

    registerPageEyebrow: 'สมัครสมาชิก',
    registerPageTitle: 'เริ่มต้นเส้นทางการเรียนรู้ของคุณ',
    registerPageDesc: 'สร้างบัญชีใหม่เพื่อปลดล็อกคอร์สเรียน จัดการโปรไฟล์ และติดตามพัฒนาการได้ในที่เดียว',
    registerPageStep1: 'กรอกข้อมูลสมาชิกให้ครบถ้วน',
    registerPageStep2: 'ตั้งค่าบัญชีและรหัสผ่าน',
    registerPageStep3: 'เริ่มเลือกคอร์สที่สนใจได้ทันที',
    registerFormTitle: 'สมัครสมาชิก',
    registerTerms: 'ฉันยอมรับเงื่อนไขการใช้งานและนโยบายความเป็นส่วนตัว',
    registerCreateAccount: 'สร้างบัญชี',
    registerHelperLink: 'มีบัญชีแล้ว? เข้าสู่ระบบ',
    registerFooterTagline: 'เริ่มต้นใช้งานได้อย่างลื่นไหลตั้งแต่ก้าวแรก',
    registerFullNamePlaceholder: 'ชื่อ-สกุล',
    registerPhonePlaceholder: 'เบอร์โทรศัพท์',
    registerEmailPlaceholder: 'อีเมล',
    registerUsernamePlaceholder: 'ชื่อผู้ใช้',
    registerPasswordPlaceholder: 'รหัสผ่าน',

    coursesPageEyebrow: 'คอร์สเรียน',
    coursesPageTitle: 'รวมคอร์สเรียนที่ออกแบบเพื่อการเติบโต',
    coursesPageDesc: 'เลือกเส้นทางที่เหมาะกับเป้าหมายของคุณ ทั้งสายพัฒนาเว็บไซต์ การออกแบบ และทักษะพร้อมทำงาน',
    coursesCtaRegister: 'สมัครเรียนตอนนี้',
    coursesCtaContact: 'สอบถามรายละเอียด',
    coursesHeroCardAria: 'ภาพรวมคอร์สเรียน',
    coursesOverviewTitle: 'ภาพรวมคอร์ส',
    coursesStatTotal: 'คอร์สทั้งหมด',
    coursesStatBootcamp: 'หลักสูตรบูตแคมป์',
    coursesStatRating: 'คะแนนรีวิวเฉลี่ย',
    popularTracksEyebrow: 'เส้นทางยอดนิยม',
    popularTracksTitle: 'คอร์สแนะนำ',
    coursesCard1Title: 'พื้นฐาน Frontend',
    coursesCard1Desc: 'ปูพื้นฐาน HTML, CSS, JavaScript พร้อมเวิร์กช็อปสร้างหน้าเว็บจริง',
    coursesCard1Meta: '12 สัปดาห์',
    coursesCard2Title: 'React และ Component Design',
    coursesCard2Desc: 'ออกแบบ UI ที่นำกลับมาใช้ซ้ำได้และเชื่อมต่อข้อมูลอย่างเป็นระบบ',
    coursesCard2Meta: '10 สัปดาห์',
    coursesCard3Title: 'ออกแบบผลิตภัณฑ์ UX/UI',
    coursesCard3Desc: 'เรียนรู้ Research, Wireframe, Prototype และการทดสอบกับผู้ใช้จริง',
    coursesCard3Meta: '8 สัปดาห์',
    coursesCard4Title: 'Backend สำหรับเว็บแอป',
    coursesCard4Desc: 'สร้าง API และจัดการฐานข้อมูลสำหรับระบบสมาชิกและคอร์สเรียน',
    coursesCard4Meta: '10 สัปดาห์',
    coursesCard5Title: 'Career Portfolio Lab',
    coursesCard5Desc: 'วางโครง Portfolio และซ้อมสัมภาษณ์เพื่อเข้าสายงานเทคโนโลยี',
    coursesCard5Meta: '6 สัปดาห์',
    coursesCard6Title: 'Team Project Bootcamp',
    coursesCard6Desc: 'ทำโปรเจกต์ทีมแบบครบวงจร ตั้งแต่แผนงานจนถึงการส่งมอบจริง',
    coursesCard6Meta: '14 สัปดาห์',
    coursesFooterTagline: 'เลือกเส้นทางของคุณและก้าวต่ออย่างมั่นใจ',

    memberPageEyebrow: 'แดชบอร์ดสมาชิก',
    memberPageTitle: 'ภาพรวมสมาชิกและความคืบหน้าการเรียน',
    memberMetric1Title: 'คอร์สที่กำลังเรียน',
    memberMetric1Value: '4 คอร์ส',
    memberMetric1Meta: 'กำลังเรียนในภาคปัจจุบัน',
    memberMetric2Title: 'อัตราการเรียนจบ',
    memberMetric2Value: '82%',
    memberMetric2Meta: 'ความคืบหน้าเฉลี่ยของทุกคอร์ส',
    memberMetric3Title: 'คลาสถัดไป',
    memberMetric3Value: '3 รายการ',
    memberMetric3Meta: 'คลาสถัดไปใน 7 วันข้างหน้า',
    memberInfoTitle: 'ข้อมูลสมาชิก',
    memberNameLabel: 'ชื่อสมาชิก',
    memberNameValue: 'นภัสสรณ์ แสงศรี',
    memberLevelLabel: 'ระดับสมาชิก',
    memberLevelValue: 'Gold',
    memberEmailLabel: 'อีเมล',
    memberEmailValue: 'member@example.com',
    memberAccountLabel: 'สถานะบัญชี',
    memberAccountValue: 'ใช้งานปกติ',
    memberEditBtn: 'แก้ไขข้อมูลสมาชิก',
    memberScheduleTitle: 'ตารางเรียนใกล้ถึง',
    memberScheduleItem1: 'Frontend Workshop - 09:00 น.',
    memberScheduleItem2: 'UX Review Session - 13:30 น.',
    memberScheduleItem3: 'Career Coaching - 10:00 น.',
    memberViewCourses: 'ดูคอร์สทั้งหมด',
    memberFooterTagline: 'ติดตามทุกความก้าวหน้าได้ในหน้าจอเดียว',

    contactPageEyebrow: 'ติดต่อ',
    contactPageTitle: 'ทีมงานพร้อมช่วยเหลือคุณ',
    contactPageDesc: 'หากต้องการรายละเอียดคอร์สเพิ่มเติม หรืออยากให้ทีมงานช่วยแนะนำเส้นทางการเรียน สามารถติดต่อได้ทันที',
    contactPhoneTitle: 'โทรศัพท์',
    contactEmailTitle: 'อีเมล',
    contactHoursTitle: 'เวลาทำการ',
    contactHoursValue: 'จันทร์ - เสาร์ 09:00 - 18:00',
    contactFooterTagline: 'ทีมงานพร้อมสนับสนุนเส้นทางการเรียนของคุณ'
  });

  Object.assign(store.translations.en, {
    navHome: 'Home',
    loginPageEyebrow: 'Login',
    loginPageTitle: 'Welcome back to JUMPFIRST',
    loginPageDesc: 'Sign in to manage courses, check schedules, and track your progress instantly.',
    loginPageHighlight1: 'Access your member dashboard',
    loginPageHighlight2: 'Get real-time schedule updates',
    loginPageHighlight3: 'Track course status anytime',
    loginFormTitle: 'Login',
    loginRemember: 'Remember me on this device',
    loginHelperLink: 'No account yet? Create one',
    loginFooterTagline: 'Member access designed for speed and security.',
    loginIdentifierPlaceholder: 'Username / Email / Phone number',
    loginPasswordPlaceholder: 'Password',

    registerPageEyebrow: 'Register',
    registerPageTitle: 'Start your learning journey today',
    registerPageDesc: 'Create a new account to unlock courses, manage your profile, and track progress in one place.',
    registerPageStep1: 'Fill in your member details',
    registerPageStep2: 'Set your account and password',
    registerPageStep3: 'Start choosing courses right away',
    registerFormTitle: 'Create account',
    registerTerms: 'I agree to the terms of service and privacy policy',
    registerCreateAccount: 'Create Account',
    registerHelperLink: 'Already have an account? Sign in',
    registerFooterTagline: 'Built for a smooth onboarding experience.',
    registerFullNamePlaceholder: 'Full name',
    registerPhonePlaceholder: 'Phone number',
    registerEmailPlaceholder: 'Email',
    registerUsernamePlaceholder: 'Username',
    registerPasswordPlaceholder: 'Password',

    coursesPageEyebrow: 'Courses',
    coursesPageTitle: 'Programs crafted for your growth',
    coursesPageDesc: 'Choose the learning path that fits your goals, from web development and design to career-ready skills.',
    coursesCtaRegister: 'Enroll Now',
    coursesCtaContact: 'Ask for Details',
    coursesHeroCardAria: 'Course overview',
    coursesOverviewTitle: 'Course Overview',
    coursesStatTotal: 'Total courses',
    coursesStatBootcamp: 'Bootcamp programs',
    coursesStatRating: 'Average rating',
    popularTracksEyebrow: 'Popular Tracks',
    popularTracksTitle: 'Recommended Courses',
    coursesCard1Title: 'Frontend Essentials',
    coursesCard1Desc: 'Build strong HTML, CSS, and JavaScript fundamentals with hands-on web workshops.',
    coursesCard1Meta: '12 weeks',
    coursesCard2Title: 'React and Component Design',
    coursesCard2Desc: 'Design reusable UI systems and connect data flows with confidence.',
    coursesCard2Meta: '10 weeks',
    coursesCard3Title: 'UX/UI Product Design',
    coursesCard3Desc: 'Learn research, wireframing, prototyping, and user testing methods.',
    coursesCard3Meta: '8 weeks',
    coursesCard4Title: 'Backend for Web Apps',
    coursesCard4Desc: 'Build APIs and manage databases for course and member systems.',
    coursesCard4Meta: '10 weeks',
    coursesCard5Title: 'Career Portfolio Lab',
    coursesCard5Desc: 'Craft your portfolio and rehearse interviews for technology roles.',
    coursesCard5Meta: '6 weeks',
    coursesCard6Title: 'Team Project Bootcamp',
    coursesCard6Desc: 'Deliver a full team project from planning through launch.',
    coursesCard6Meta: '14 weeks',
    coursesFooterTagline: 'Choose your path and move forward with confidence.',

    memberPageEyebrow: 'Member Dashboard',
    memberPageTitle: 'Member overview and learning progress',
    memberMetric1Title: 'Active Courses',
    memberMetric1Value: '4 courses',
    memberMetric1Meta: 'Currently enrolled this term',
    memberMetric2Title: 'Completion Rate',
    memberMetric2Value: '82%',
    memberMetric2Meta: 'Average progress across all courses',
    memberMetric3Title: 'Upcoming Sessions',
    memberMetric3Value: '3 items',
    memberMetric3Meta: 'Scheduled in the next 7 days',
    memberInfoTitle: 'Member Information',
    memberNameLabel: 'Member Name',
    memberNameValue: 'Napatsorn Saengsri',
    memberLevelLabel: 'Membership Tier',
    memberLevelValue: 'Gold',
    memberEmailLabel: 'Email',
    memberEmailValue: 'member@example.com',
    memberAccountLabel: 'Account Status',
    memberAccountValue: 'Active',
    memberEditBtn: 'Edit Member Profile',
    memberScheduleTitle: 'Upcoming Schedule',
    memberScheduleItem1: 'Frontend Workshop - 9:00 AM',
    memberScheduleItem2: 'UX Review Session - 1:30 PM',
    memberScheduleItem3: 'Career Coaching - 10:00 AM',
    memberViewCourses: 'View All Courses',
    memberFooterTagline: 'Track every learning milestone in one place.',

    contactPageEyebrow: 'Contact',
    contactPageTitle: 'Our team is ready to help',
    contactPageDesc: 'If you need course details or guidance on your learning path, feel free to reach out anytime.',
    contactPhoneTitle: 'Phone',
    contactEmailTitle: 'Email',
    contactHoursTitle: 'Business Hours',
    contactHoursValue: 'Monday - Saturday, 9:00 AM - 6:00 PM',
    contactFooterTagline: 'We are here to support your learning journey.'
  });

  store.textBindings = [
    ...store.textBindings,
    ['body[data-page] .site-nav a[href="../index.html"]', 'navHome'],
    ['body[data-page] .site-nav a[href="courses.html"]', 'navCourses'],
    ['body[data-page] .site-nav a[href="member-dashboard.html"]', 'navDashboard'],
    ['body[data-page] .site-nav a[href="contact.html"]', 'navContact'],
    ['body[data-page] .nav-actions .btn.btn-secondary[href="login.html"]', 'login'],
    ['body[data-page] .nav-actions .btn.btn-secondary[href="register.html"]', 'register'],
    ['body[data-page] .nav-actions .btn.btn-primary[href="register.html"]', 'register'],

    ['body[data-page="login"] .hero-copy .eyebrow', 'loginPageEyebrow'],
    ['body[data-page="login"] .hero-copy h1', 'loginPageTitle'],
    ['body[data-page="login"] .hero-copy > p:not(.eyebrow)', 'loginPageDesc'],
    ['body[data-page="login"] .hero-highlights li:nth-child(1)', 'loginPageHighlight1'],
    ['body[data-page="login"] .hero-highlights li:nth-child(2)', 'loginPageHighlight2'],
    ['body[data-page="login"] .hero-highlights li:nth-child(3)', 'loginPageHighlight3'],
    ['body[data-page="login"] .auth-form h2', 'loginFormTitle'],
    ['body[data-page="login"] .check-row span', 'loginRemember'],
    ['body[data-page="login"] .auth-form .btn.btn-primary', 'login'],
    ['body[data-page="login"] .helper-links a', 'loginHelperLink'],
    ['body[data-page="login"] .footer-wrap p:last-child', 'loginFooterTagline'],

    ['body[data-page="register"] .hero-copy .eyebrow', 'registerPageEyebrow'],
    ['body[data-page="register"] .hero-copy h1', 'registerPageTitle'],
    ['body[data-page="register"] .hero-copy > p:not(.eyebrow)', 'registerPageDesc'],
    ['body[data-page="register"] .hero-copy .step:nth-child(1) p', 'registerPageStep1'],
    ['body[data-page="register"] .hero-copy .step:nth-child(2) p', 'registerPageStep2'],
    ['body[data-page="register"] .hero-copy .step:nth-child(3) p', 'registerPageStep3'],
    ['body[data-page="register"] .auth-form h2', 'registerFormTitle'],
    ['body[data-page="register"] .check-row span', 'registerTerms'],
    ['body[data-page="register"] .auth-form .btn.btn-primary', 'registerCreateAccount'],
    ['body[data-page="register"] .helper-links a', 'registerHelperLink'],
    ['body[data-page="register"] .footer-wrap p:last-child', 'registerFooterTagline'],

    ['body[data-page="courses"] .hero-copy .eyebrow', 'coursesPageEyebrow'],
    ['body[data-page="courses"] .hero-copy h1', 'coursesPageTitle'],
    ['body[data-page="courses"] .hero-copy > p:not(.eyebrow)', 'coursesPageDesc'],
    ['body[data-page="courses"] .hero-actions .btn.btn-primary', 'coursesCtaRegister'],
    ['body[data-page="courses"] .hero-actions .btn.btn-outline', 'coursesCtaContact'],
    ['body[data-page="courses"] .card-body h3', 'coursesOverviewTitle'],
    ['body[data-page="courses"] .stats-grid div:nth-child(1) span', 'coursesStatTotal'],
    ['body[data-page="courses"] .stats-grid div:nth-child(2) span', 'coursesStatBootcamp'],
    ['body[data-page="courses"] .stats-grid div:nth-child(3) span', 'coursesStatRating'],
    ['body[data-page="courses"] .section-heading .eyebrow', 'popularTracksEyebrow'],
    ['body[data-page="courses"] .section-heading h2', 'popularTracksTitle'],
    ['body[data-page="courses"] .feature-card:nth-child(1) h3', 'coursesCard1Title'],
    ['body[data-page="courses"] .feature-card:nth-child(1) p', 'coursesCard1Desc'],
    ['body[data-page="courses"] .feature-card:nth-child(1) span', 'coursesCard1Meta'],
    ['body[data-page="courses"] .feature-card:nth-child(2) h3', 'coursesCard2Title'],
    ['body[data-page="courses"] .feature-card:nth-child(2) p', 'coursesCard2Desc'],
    ['body[data-page="courses"] .feature-card:nth-child(2) span', 'coursesCard2Meta'],
    ['body[data-page="courses"] .feature-card:nth-child(3) h3', 'coursesCard3Title'],
    ['body[data-page="courses"] .feature-card:nth-child(3) p', 'coursesCard3Desc'],
    ['body[data-page="courses"] .feature-card:nth-child(3) span', 'coursesCard3Meta'],
    ['body[data-page="courses"] .feature-card:nth-child(4) h3', 'coursesCard4Title'],
    ['body[data-page="courses"] .feature-card:nth-child(4) p', 'coursesCard4Desc'],
    ['body[data-page="courses"] .feature-card:nth-child(4) span', 'coursesCard4Meta'],
    ['body[data-page="courses"] .feature-card:nth-child(5) h3', 'coursesCard5Title'],
    ['body[data-page="courses"] .feature-card:nth-child(5) p', 'coursesCard5Desc'],
    ['body[data-page="courses"] .feature-card:nth-child(5) span', 'coursesCard5Meta'],
    ['body[data-page="courses"] .feature-card:nth-child(6) h3', 'coursesCard6Title'],
    ['body[data-page="courses"] .feature-card:nth-child(6) p', 'coursesCard6Desc'],
    ['body[data-page="courses"] .feature-card:nth-child(6) span', 'coursesCard6Meta'],
    ['body[data-page="courses"] .footer-wrap p:last-child', 'coursesFooterTagline'],

    ['body[data-page="member-dashboard"] .section-heading .eyebrow', 'memberPageEyebrow'],
    ['body[data-page="member-dashboard"] .section-heading h1', 'memberPageTitle'],
    ['body[data-page="member-dashboard"] .dashboard-metrics .feature-card:nth-child(1) h3', 'memberMetric1Title'],
    ['body[data-page="member-dashboard"] .dashboard-metrics .feature-card:nth-child(1) .metric-value', 'memberMetric1Value'],
    ['body[data-page="member-dashboard"] .dashboard-metrics .feature-card:nth-child(1) span', 'memberMetric1Meta'],
    ['body[data-page="member-dashboard"] .dashboard-metrics .feature-card:nth-child(2) h3', 'memberMetric2Title'],
    ['body[data-page="member-dashboard"] .dashboard-metrics .feature-card:nth-child(2) .metric-value', 'memberMetric2Value'],
    ['body[data-page="member-dashboard"] .dashboard-metrics .feature-card:nth-child(2) span', 'memberMetric2Meta'],
    ['body[data-page="member-dashboard"] .dashboard-metrics .feature-card:nth-child(3) h3', 'memberMetric3Title'],
    ['body[data-page="member-dashboard"] .dashboard-metrics .feature-card:nth-child(3) .metric-value', 'memberMetric3Value'],
    ['body[data-page="member-dashboard"] .dashboard-metrics .feature-card:nth-child(3) span', 'memberMetric3Meta'],
    ['body[data-page="member-dashboard"] .member-card h2', 'memberInfoTitle'],
    ['body[data-page="member-dashboard"] .member-row:nth-of-type(1) strong', 'memberNameLabel'],
    ['body[data-page="member-dashboard"] .member-row:nth-of-type(1) span', 'memberNameValue'],
    ['body[data-page="member-dashboard"] .member-row:nth-of-type(2) strong', 'memberLevelLabel'],
    ['body[data-page="member-dashboard"] .member-row:nth-of-type(2) span', 'memberLevelValue'],
    ['body[data-page="member-dashboard"] .member-row:nth-of-type(3) strong', 'memberEmailLabel'],
    ['body[data-page="member-dashboard"] .member-row:nth-of-type(3) span', 'memberEmailValue'],
    ['body[data-page="member-dashboard"] .member-row:nth-of-type(4) strong', 'memberAccountLabel'],
    ['body[data-page="member-dashboard"] .member-row:nth-of-type(4) span', 'memberAccountValue'],
    ['body[data-page="member-dashboard"] .member-card .btn.btn-secondary', 'memberEditBtn'],
    ['body[data-page="member-dashboard"] .register-panel h2', 'memberScheduleTitle'],
    ['body[data-page="member-dashboard"] .register-panel .step:nth-child(2) p', 'memberScheduleItem1'],
    ['body[data-page="member-dashboard"] .register-panel .step:nth-child(3) p', 'memberScheduleItem2'],
    ['body[data-page="member-dashboard"] .register-panel .step:nth-child(4) p', 'memberScheduleItem3'],
    ['body[data-page="member-dashboard"] .register-panel .btn.btn-primary', 'memberViewCourses'],
    ['body[data-page="member-dashboard"] .footer-wrap p:last-child', 'memberFooterTagline'],

    ['body[data-page="contact"] .contact-wrap .eyebrow', 'contactPageEyebrow'],
    ['body[data-page="contact"] .contact-wrap h1', 'contactPageTitle'],
    ['body[data-page="contact"] .contact-wrap > div > p:not(.eyebrow)', 'contactPageDesc'],
    ['body[data-page="contact"] .contact-points .info-card:nth-child(1) h3', 'contactPhoneTitle'],
    ['body[data-page="contact"] .contact-points .info-card:nth-child(2) h3', 'contactEmailTitle'],
    ['body[data-page="contact"] .contact-points .info-card:nth-child(3) h3', 'contactHoursTitle'],
    ['body[data-page="contact"] .contact-points .info-card:nth-child(3) p', 'contactHoursValue'],
    ['body[data-page="contact"] .footer-wrap p:last-child', 'contactFooterTagline']
  ];

  store.placeholderBindings = [
    ...store.placeholderBindings,
    ['body[data-page="login"] .auth-form input[type="text"]', 'loginIdentifierPlaceholder'],
    ['body[data-page="login"] .auth-form input[type="password"]', 'loginPasswordPlaceholder'],
    ['body[data-page="register"] .auth-form input[type="text"]:nth-of-type(1)', 'registerFullNamePlaceholder'],
    ['body[data-page="register"] .auth-form input[type="tel"]', 'registerPhonePlaceholder'],
    ['body[data-page="register"] .auth-form input[type="email"]', 'registerEmailPlaceholder'],
    ['body[data-page="register"] .auth-form input[type="text"]:nth-of-type(2)', 'registerUsernamePlaceholder'],
    ['body[data-page="register"] .auth-form input[type="password"]', 'registerPasswordPlaceholder']
  ];

  window.JUMPFIRST_CONTENT = store;
})();
